# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_created=True)),
                ('codigo_barra', models.CharField(max_length=3000)),
                ('descripcion', models.CharField(max_length=600)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('impuesto_interno', models.IntegerField(blank=True, default=0, null=True)),
                ('alicuota_iva', models.IntegerField(blank=True, default=21, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('causa_baja', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'Árticulos',
                'verbose_name_plural': 'Árticulos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPreciosCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateField(auto_created=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
            options={
                'verbose_name': 'Historial de Precios de Compra',
                'verbose_name_plural': 'Historiales de Precios de Compras',
            },
        ),
        migrations.CreateModel(
            name='HistorialPreciosVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateField(auto_created=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
            options={
                'verbose_name': 'Historial de Precios de Venta',
                'verbose_name_plural': 'Historiales de Precios de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='PrecioVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('efectivo', 'Efectivo')], max_length=600)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
            options={
                'verbose_name': 'Precio de Venta',
                'verbose_name_plural': 'Precios de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.Marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.Rubro'),
        ),
    ]
