# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioventa',
            name='articulo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='PrecioVenta',
        ),
    ]
