# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20170514_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_debito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
