# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20180408_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
