# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('articulos', '0006_auto_20180412_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal'),
        ),
    ]
