# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_articulo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad_vendida',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
