# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_articulo_cantidad_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='no_suma_caja',
            field=models.BooleanField(default=False),
        ),
    ]
