# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_articulo_no_suma_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias_web'),
        ),
    ]
