# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio_web',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
