# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_articulo_precio_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock_web',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
