# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('punto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Puntos de configuraciones',
                'verbose_name': 'Punto de configuración',
            },
        ),
    ]
