# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=600)),
                ('apellido', models.TextField(blank=True, max_length=800, null=True)),
                ('direccion', models.TextField(blank=True, max_length=800, null=True)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('causa_baja', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('celular', 'celular'), ('email', 'email'), ('telefono_trabajo', 'Telefono del Trabajo'), ('telefono_casa', 'Telefono de la casa'), ('telefono1', 'Telefono 1'), ('telefono_casa2', 'Telefono 2')], max_length=200)),
                ('descripcion', models.CharField(max_length=600)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('causa_baja', models.TextField(blank=True, max_length=600, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
                'verbose_name': 'Contacto',
            },
        ),
    ]
