# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models

import django

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
