# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
