# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20180417_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_alta',
        ),
    ]
