# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
