# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
