# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
