# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20180614_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
