# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_efectivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='efectivo',
            new_name='credito',
        ),
    ]
