# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
