# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cuota_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos_premium',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
