# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20170528_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='causa_baja',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
