# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True)),
                ('motivo', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('mantenimiento', 'mantenimiento'), ('varios', 'Varios')], max_length=600)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'verbose_name': 'Gasto',
            },
        ),
    ]
