# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='motivo',
            field=models.CharField(max_length=600),
        ),
    ]
