# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('gastos', '0002_auto_20170609_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal'),
        ),
    ]
