# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ManyToManyField(blank=True, to='perfiles.Permiso')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
