# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('gastos_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastomensual',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gasto_mensual_sucursal', to='sucursales.Sucursal'),
        ),
        migrations.AddField(
            model_name='motivo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivo_sucursal', to='sucursales.Sucursal'),
        ),
    ]
