# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20170530_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
