# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_porcentaje_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_no_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
