# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ventas', '0006_auto_20180424_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal'),
        ),
    ]
