# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_remove_venta_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloventa',
            name='stock_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
