# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_articuloventa_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloventa',
            name='stock_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
